### ISSUE TITLE
構造ファイルの移動

### ISSUE THREAD

**Issue by shimizu123321** [ichibha/setupMaezono#1]
初めまして。御著書「動かして理解する第一原理電子状態計算」を拝読している者です。

　御著書pp.46-47に記載されている方法で、quartz_alpha.dcifをstructureに保管する方法についてお聞きしたく連絡いたしました。

　AMCSDからデータのダウンロードを終え、私のPCのダウンロードファイルにAMS_DATA.cifが入っていることを確認しております。しかし、このファイルをquartz_alpha.dcifとして保管することができておりません。すみませんが、以下の3点についてご教授いただけないでしょうか？

　現在、maezonoファイルは、「PC/OS (C:)/ユーザー」に保管されており、ubuntuでの操作で以下の点で行き詰まっております。

1. work/structureの階層が構築できない
%cd
%mkdir -p work/structure
と入力していますが、maezonoファイルに「workファイル」「structureファイル」がGUIで確認できないのですが、これは仕様なのでしょうか？

2. pwdと入力しても、 「/Users/rm/work/structure」が表示されない。
%pwdと入力したところ、「/home/maezono」と表示されるのですが、問題ないのでしょうか？ちなみに、コマンドlsを入力すると
Downloads(赤字) get-pip.py(白字) home structure work(青字)
と表示されました。

3. AMS_DATA.cifを~work structureに移動できない
mv ~/Downloads/AMS_DATA.cif .と入力したのですが、

mv: cannot stat '/home/maezono/Downloads/AMS_DATA.cif': No such file or directory

と表示されました。何が問題なのでしょうか？

**Comment by ichibha** [comment]
Shimizu123321様、

workディレクトリはwindows上でどちらに作られましたでしょうか??
ホームディレクトリ名がmaezonoで無いならば、§2.2以降のすべての操作において
maezonoをご自身のものに読み替える必要があります。
ご確認いただけますでしょうか??

市場

**Comment by shimizu123321** [comment]
市場様

　唐突な質問にかかわらず、ご返信ありがとうございました。

　CUIでの操作をあまりわかっておらず恐縮ですが、ご著書のp.34とまったく同じコマンドを入力しました。
　本当に基礎から出申し訳ないのですが、ホームディレクトリの確認は、「cd」「pwd」の順に入力して表示されるもので間違いないでしょうか？そのように入力したところ、「/home/maezono」
と表示されました。
　「maezono」が含まれていたのでp.35の記述は無視してもよいと判断したのですが、私の場合は、自分のユーザーネームに読み替える必要があるのでしょうか？

　以上、よろしくお願いいたします。

**Comment by ichibha** [comment]
Ubuntu上のホームディレクトリ名はmaezonoとしておられますので、こちらを読み替える必要はありません。
一方、windowsの方のホームディレクトリ名がmaezonoでない場合、こちらは読み替える必要があります。
Windows上でのworkディレクトリ、および、DownloadsディレクトリのUsers以下のパスを教えていただけますでしょうか??
本著の場合、
Users/maezono/work および Users/maezono/Downloads

市場

**Comment by shimizu123321** [comment]
Windowsのホームディレクトリと区別されていたのですね。承知しました。

　Windowsのディレクトリは、コマンドプロンプトで確認すればよいでしょうか？すみませんが、コマンドプロンプトも今回初めて触ったので、どう操作すればWindows上でのworkディレクトリ、および、DownloadsディレクトリのUsers以下のパスが確認できるかがわかりません。

　すみませんが、パスの確認方法もご教授よろしくお願いいたします。

**Comment by ichibha** [comment]
下記をご参照ください。
https://pc-karuma.net/windows10-file-full-path-copy/ <https://pc-karuma.net/windows10-file-full-path-copy/>

市場

**Comment by shimizu123321** [comment]
遅くなりすみません。

　windowsのパスは以下だと思います。
　ちなみに、workディレクトリはたった今作り直しました。

　Users/ganzg/work
　Users/ganzg/Downloads

　ところで、Ubuntuでworkディレクトリを作り直そうと"mkdir work"と入力したところ、

mkdir: cannot create directory 'work' i: File exists

と表示されたので、GUIからganzgファイルに直接workファイルを作り直したのですが、問題なかったでしょうか？

　よろしくお願いいたします。

**Comment by ichibha** [comment]
> GUIからganzgファイルに直接workファイルを作り直したのですが、問題なかったでしょうか？
> 

windows上でもともと作成していた/Users/ganzg/workを削除し、workディレクトリを作り直した
ということでしょうか?? 問題ないと思います。

>> 3. AMS_DATA.cifを~work/structureに移動できない
>> mv ~/Downloads/AMS_DATA.cif .と入力したのですが、
>> mv: cannot stat '/home/maezono/Downloads/AMS_DATA.cif': No such file or directory
>> と表示されました。何が問題なのでしょうか？

こちらは、Downloadsが/mnt/c/Users/ganzg/Downloadsにあるにも拘らず、
/mnt/c/Users/maezono/Downloadsへのリンクを~/Downloadsに貼ってしまったのが原因です。
Ubuntu上ではじめに貼ったリンクを削除
cd
rm Downloads
し、リンクを貼り直してください: 
ln -s /mnt/c/Users/ganzg/Downloads

>> 1. 
>> work/structureの階層が構築できない
>> %cd
>> %mkdir -p work/structure
>> と入力していますが、maezonoファイルに「workファイル」「structureファイル」がGUIで確認できないのですが、これは仕様なのでしょうか？

>> 2. 
>> pwdと入力しても、 「/Users/rm/work/structure」が表示されない。
>> %pwdと入力したところ、「/home/maezono」と表示されるのですが、問題ないのでしょうか？ちなみに、コマンドlsを入力すると
>> Downloads(赤字) get-pip.py(白字) home structure work(青字)
>> と表示されました。

これらの問題を直すのには2つの修正が必要です:
まず、恐縮なのですが、 
ln -s /work /mnt/c/Users/maezono/work
は書籍の記載ミスで、正しくは
ln -s /mnt/c/Users/maezono/work
です。加えてshimizuさんの場合にはDownloadsの場合と同様に
maezonoをganzgに変更する必要があります。
次の手順でリンクを貼り直してください: 
cd
rm work
ln -s /mnt/c/Users/ganzg/work

**Comment by shimizu123321** [comment]
教えていただきありがとうございます。現段階で確認しているところまでお知らせします。

>windows上でもともと作成していた/Users/ganzg/workを削除し、workディレクトリを作り直した
ということでしょうか?? 
　いえ、windows上にはもともとworkディレクトリはありませんでした。そのため、Ubuntuでworkディレクトリを作り直そうと"mkdir work"と入力したのですが、"mkdir: cannot create directory 'work' i: File exists"が表示されたので、GUIを眺めながらganzgファイルにworkファイルを作りました。この操作は問題ないでしょうか？

　ちなみに、"mkdir: cannot create directory 'work' i: File exists"はなぜ表示されたのでしょうか？すみませんが、こちらもお願いします。

**Comment by ichibha** [comment]
shimizuさま、

返信遅れまして申し訳ございません。

workフォルダに関する書籍の記載が間違っていたため訂正させていただきます。
2.2.1の初めのコマンドで
-----------------------------------------
% cd
% mkdir work
-----------------------------------------
とあるのですが、windowsの場合には
% mkdir /mnt/c/Users/(ユーザー名)/work
としなければならない、というのが一つ目の修正点です。
その上で、/mnt/c/Users/(ユーザー名)/workから(Ubuntuのホームディレクトリ)/workに
リンクを貼るのに
誤: % ln -s /work/ /mnt/c/Users/(ユーザー名)/work に替えて
正:
% cd 
% ln -s /mnt/c/Users/(ユーザー名)/work
を実行する必要があります。

shimizuさんの場合には、ganzgディレクトリに既にworkディレクトリを
作られたとのことですので、
% mkdir /mnt/c/Users/(ユーザー名)/work
は省くことができます。
% cd 
% ln -s /mnt/c/Users/(ユーザー名)/work
を実行し、エラーが生じた場合、そちらを教えていただけますでしょうか??

市場

**Comment by shimizu123321** [comment]
ありがとうございます。さっそく実行したところ、

In: failed to create symbolic link ' ./work' : File exists

と表示されました。これは、「すでにリンクが張られている」を意味しているのでしょうか？
　よろしくお願いいたします。

**Comment by ichibha** [comment]
おっしゃる通りかと思います。
% cd 
% rm work
でリンクを一度消してからリンクを貼り直し、
% ls work
でフォルダの中身が見られるかご確認いただけますでしょうか??

市場

**Comment by shimizu123321** [comment]
ありがとうございます。

　とりあえず

% cd
% rm work

を実行したところ、rm: cannot remove 'work' : Is a directoryと表示されました。'work'はディレクトリだから消去できないというのはどういうことでしょうか(私のPCの不具合でしょうか)？

　ちなみに、ls work と入力したところ、setupMaezono structure workと表示されました。

**Comment by ichibha** [comment]
~/workにあるのが、リンクではなくフォルダということですね。
 こちらは
% cd
% rm -rf work
で削除することができますので、それからリンクを貼り直していただき、
ページ35以下をすすめていただけますでしょうか？？

市場

**Comment by shimizu123321** [comment]
rmを実行できました。次の操作なのですが、% mkdir /mnt/c/Users/(ユーザー名)/workを実行すると、

mkdir: cannot create directory ‘/mnt/c/Users/ganzg/work’: File exists

と表示されました。そのまま

% cd
% ln -s /mnt/c/Users/(ユーザー名)/work

を実行しましたが、ls workと入力しても何も表示されませんでした。lsと打つと、

Downloads(赤字) get-pip.py(白字) home structure (青字) work(水色) ダウンロード(赤)

と表示されました。これは順調にできているのでしょうか？

**Comment by ichibha** [comment]
% cd
% rm -rf work
% ln -s /mnt/c/Users/(username)/work
としていただけますと、
windows上の/Users/(username)/workからUbuntu上の~/workに
リンクが貼られますので、ページ35以降を進めていただくことが
できます。

**Comment by shimizu123321** [comment]
ありがとうございます。p.362.2.3まで進みました。

続いて、tar -xvf linuxBasic.tar.gzを入力したのところ、

tar: linuxBasic.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

と表示されたのですが、これは問題ないのでしょうか？

また、lsと入力したところ、setupMaezono(緑の網掛け)が表示されました。

**Comment by ichibha** [comment]
>>次に「̅/work/setupMaezono」以下に移動します. 

展開前にsetupMaezonoにcdで移動してください。

**Comment by shimizu123321** [comment]
ありがとうございます。第二章は無事に終えました。

　続いてp.47には、

pwd
       /Users/rm/work/structure

と書いてあるのですが、「これはpwdと入力すると、       /Users/rm/work/structure」が表示されるということでしょうか？

　また、mv ~/Downloads/AMS_DATA.cif .とすると、WindowsのダウンロードディレクトリからCIFファイルがなくなってしまいましたが、ubuntu上のコマンドで確認するしかないでしょうか？
　ちなみに、ls -lと入力すると、quartz_alpha.dcifが表示されましたので、ここまではおそらく成功していると思います。

**Comment by shimizu123321** [comment]
現在、p.48まで進めました。次に、VESTAでCIFファイルを開きたいのですが、ubuntu内のCIFファイルを読み込ませるにはどうすればよいでしょうか？

**Comment by ichibha** [comment]
ubuntu上の~/workは
windows上の/Users/(ユーザー名)/work
へのショートカットなので、work以下に置いた構造ファイルはwindows上では
/Users/(ユーザー名)/work
に見つけられます。

市場

**Comment by shimizu123321** [comment]
すみません、やはり見つけられず、VESTAでCIFファイルを開けない状態で止まっています。

　そもそもWindows上にもアイコンが見当たらないのですが、何かのバグでしょうか？

**Comment by ichibha** [comment]
> 3. AMS_DATA.cifを~work/structureに移動できない
> mv ~/Downloads/AMS_DATA.cif .と入力したのですが、
> mv: cannot stat '/home/maezono/Downloads/AMS_DATA.cif': No such file or directory
> と表示されました。何が問題なのでしょうか？
こちらの問題は解決いたしましたでしょうか??

市場

**Comment by shimizu123321** [comment]
おそらく解決できています。mv ~/Downloads/AMS_DATA.cif .と入力したところWindowsのDownloadsディレクトリからCIFファイルがなくなり、ls -lと入力するとquartz_alpha.dcifが表示されました。

**Comment by ichibha** [comment]
> ls -lと入力するとquartz_alpha.dcifが表示されました。
> 
同じディレクトリでpwdを叩くと何が表示されますか??

また、
cd 
ls -l
を入力すると何が表示されますか??

上記2つを教えていただけますでしょうか??

市場

**Comment by shimizu123321** [comment]
すみません、同じディレクトリというとどこでしょうか？quartz_alpha.dcifが表示されたディレクトリですと、cdと打ったところです。その後pwdと打つと/home/maezonoと表示されました。

また、
cd
ls -l
を入力すると、以下が表示されました。

total 1864
lrwxrwxrwx 1 maezono maezono      28 Dec 11 11:11 Downloads -> /mnt/c/Users/ganzg/Downloads
-rwxrwxrwx 1 maezono maezono    1300 Dec 13 05:23 crysto_alpha.dcif
-rwxrwxrwx 1 maezono maezono    4830 Dec 13 05:25 crysto_beta.dcif
-rw-r--r-- 1 maezono maezono 1886796 Nov 27 16:29 get-pip.py
drwxr-xr-x 1 maezono maezono     512 Nov 29 16:42 home
-rwxrwxrwx 1 maezono maezono    1058 Nov 28 01:46 quartz_alpha.dcif
-rwxrwxrwx 1 maezono maezono    1056 Dec 13 05:20 quartz_beta.dcif
drwxr-xr-x 1 maezono maezono     512 Nov 29 16:42 structure
lrwxrwxrwx 1 maezono maezono      23 Dec 11 08:55 work -> /mnt/c/Users/ganzg/work
lrwxrwxrwx 1 maezono maezono      37 Dec  3 16:17 ダウンロード -> /mnt/c/Users/ganzg/ダウンロード

ちなみに、cd workと入力後ls -lと打つと、以下が表示されました。
total 0
drwxrwxrwx 1 maezono maezono 512 Dec 11 10:57 setupMaezono
drwxrwxrwx 1 maezono maezono 512 Dec 11 11:08 structure

どうでしょうか？何かヒントになりそうなことはあるでしょうか？すみませんが、よろしくお願いします。

**Comment by ichibha** [comment]
次に、
ls /mnt/c/Users/ganzg/
をみると何がみえるか教えていただけますでしょうか??

市場

**Comment by shimizu123321** [comment]
以下が表示されました。おそらく、私のPCのファイル名のリストです。

'3D Objects'
 AppData
'Application Data'
 Contacts
 Cookies
'Creative Cloud Files'
 Desktop
 Documents
 Downloads
 Favorites
 IntelGraphicsProfiles
 Links
'Local Settings'
 MicrosoftEdgeBackups
 Music
'My Documents'
 NTUSER.DAT
 NTUSER.DAT{817c6eef-79e5-11ea-a7f2-d81265b80f00}.TM.blf
 NTUSER.DAT{817c6eef-79e5-11ea-a7f2-d81265b80f00}.TMContainer00000000000000000001.regtrans-ms
 NTUSER.DAT{817c6eef-79e5-11ea-a7f2-d81265b80f00}.TMContainer00000000000000000002.regtrans-ms
 NetHood
 OneDrive
'OneDrive - 〇〇〇〇〇〇〇' (〇 : 諸事情により伏字です)
 Pictures
 PrintHood
 Recent
'Saved Games'
 Searches
 SendTo
 Templates
 Videos
'VirtualBox VMs'
 ntuser.dat.LOG1
 ntuser.dat.LOG2
 ntuser.ini
 work
'スタート メニュー'

**Comment by ichibha** [comment]
> ntuser.ini
> work
> 'スタート メニュー'
> 

では、このworkはwindowsから見え、その中に構造ファイルがありますね。
すると、構造ファイルまでwindows上でたどりつくことができるとおもうのですが、
ためしていただけますでしょうか??

**Comment by shimizu123321** [comment]
すみません。workは見えるのですが、中に入っているのは、setupMaezonoファイル(ダウンロードファイル)とstructureファイル(空)が入っているだけです。これが先に進めない原因でしょうか？

**Comment by ichibha** [comment]
下記の編みかけの間で、~/work/structureまでcdコマンドで移動する必要があります。

**Comment by shimizu123321** [comment]
cd work/structureで移動できました。続いて、pwdと入力すると、以下が表示されました。

/home/maezono/work/structure

　ちなみに、maezono@DESKTOP-KV9KL02:~/work/structure$と表示されているときにls -lと入力すると、

total 0

と表示されました。これは、CIFファイルが適切に移動できていないということでしょうか？

**Comment by ichibha** [comment]
> これは、CIFファイルが適切に移動できていないということでしょうか？
> 

すくなくとも、そちらのディレクトリに現在なにもファイルがないことを意味しています。
市場

**Comment by shimizu123321** [comment]
承知しました。すると、ご著書の通りコマンドを実行したのですが、何が問題だったのでしょうか？

　p.47の

pwd
     /Users/rm/work/structure

または

mv ~//Downloads/AMS_DATA.cif .

でミスが起きたと考えているのですが、どうでしょうか？

　よろしくお願いいたします。

**Comment by shimizu123321** [comment]
すみませんが、現状での対応策も教えてくださると助かります。

**Comment by ichibha** [comment]
もともと本著では~/workにディレクトリを作り、Windowsの方にリンクするという流れでした。(時点A)
しかしながら、この方法ですとGUIでの表示に難がありましたので、
Windowsの方にディレクトリを作り、~/workにリンクしていただきました。

時点Aでmvコマンドを実行したとするならば、~/workを消したのと一緒にcifファイルも消えてしまっているので、
もう一度Downloadsにcifファイルを用意し、再度mvコマンドを実行していただく必要があります。

市場

**Comment by shimizu123321** [comment]
ありがとうございました。構造データを移し、VESTAで変換するところまで進めました。

　続いてなのですが、cif2cellがインストールできていなかったようで、cif2cellを実行できませんでした。2.4.1に書いてあるように、

cd
sudo pip3 install cif2cell

と入力してパスワードを入力したところ、以下の表示が出てきました。

Collecting cif2cell
  Using cached cif2cell-2.0.0a2-py2.py3-none-any.whl (2.1 MB)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from cif2cell) (1.14.0)
Collecting PyCifRW==4.4; python_version >= "3"
  Using cached PyCifRW-4.4.tar.gz (1.1 MB)
Building wheels for collected packages: PyCifRW
  Building wheel for PyCifRW (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9onaa7ot/pycifrw/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9onaa7ot/pycifrw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yj4c44pz
       cwd: /tmp/pip-install-9onaa7ot/pycifrw/
  Complete output (31 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/CifFile
  copying src/__init__.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/CifFile_module.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/yapps3_compiled_rt.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/YappsStarParser_1_1.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/YappsStarParser_1_0.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/YappsStarParser_STAR2.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/YappsStarParser_2_0.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/StarFile.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/TypeContentsParser.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/parsetab.py -> build/lib.linux-x86_64-3.8/CifFile
  creating build/lib.linux-x86_64-3.8/CifFile/drel
  copying src/drel/drel_ast_yacc.py -> build/lib.linux-x86_64-3.8/CifFile/drel
  copying src/drel/drel_lex.py -> build/lib.linux-x86_64-3.8/CifFile/drel
  copying src/drel/drel_runtime.py -> build/lib.linux-x86_64-3.8/CifFile/drel
  copying src/drel/parsetab.py -> build/lib.linux-x86_64-3.8/CifFile/drel
  copying src/drel/py_from_ast.py -> build/lib.linux-x86_64-3.8/CifFile/drel
  copying src/drel/__init__.py -> build/lib.linux-x86_64-3.8/CifFile/drel
  running build_ext
  building 'CifFile.StarScan' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/src
  creating build/temp.linux-x86_64-3.8/src/lib
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c src/lib/lex.yy.c -o build/temp.linux-x86_64-3.8/src/lib/lex.yy.o
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for PyCifRW
  Running setup.py clean for PyCifRW
Failed to build PyCifRW
Installing collected packages: PyCifRW, cif2cell
    Running setup.py install for PyCifRW ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9onaa7ot/pycifrw/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9onaa7ot/pycifrw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-__a4srbq/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/PyCifRW
         cwd: /tmp/pip-install-9onaa7ot/pycifrw/
    Complete output (31 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/CifFile
    copying src/__init__.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/CifFile_module.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/yapps3_compiled_rt.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/YappsStarParser_1_1.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/YappsStarParser_1_0.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/YappsStarParser_STAR2.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/YappsStarParser_2_0.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/StarFile.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/TypeContentsParser.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/parsetab.py -> build/lib.linux-x86_64-3.8/CifFile
    creating build/lib.linux-x86_64-3.8/CifFile/drel
    copying src/drel/drel_ast_yacc.py -> build/lib.linux-x86_64-3.8/CifFile/drel
    copying src/drel/drel_lex.py -> build/lib.linux-x86_64-3.8/CifFile/drel
    copying src/drel/drel_runtime.py -> build/lib.linux-x86_64-3.8/CifFile/drel
    copying src/drel/parsetab.py -> build/lib.linux-x86_64-3.8/CifFile/drel
    copying src/drel/py_from_ast.py -> build/lib.linux-x86_64-3.8/CifFile/drel
    copying src/drel/__init__.py -> build/lib.linux-x86_64-3.8/CifFile/drel
    running build_ext
    building 'CifFile.StarScan' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/src
    creating build/temp.linux-x86_64-3.8/src/lib
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c src/lib/lex.yy.c -o build/temp.linux-x86_64-3.8/src/lib/lex.yy.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9onaa7ot/pycifrw/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9onaa7ot/pycifrw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-__a4srbq/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/PyCifRW Check the logs for full command output.
WARNING: You are using pip version 20.2.4; however, version 20.3.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

　これはどうすれば解決できるでしょうか？すみませんが、よろしくお願いいたします。

**Comment by shimizu123321** [comment]
教えてくださったコマンドを実行しました。こちらは問題なく終えられたと思います。

　一方、

cd
sudo pip3 install cif2cell

を実行しましたが、再び昨日と同じものが表示されました。

　ほかにはどのような対応策がありますでしょうか？すみませんが、よろしくお願いいたします。

**Comment by shimizu123321** [comment]
また、表示の最後を参考に、

/usr/bin/python3 -m pip install --upgrade pip

を実行してみたところ、以下のように表示されました。

efaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in ./.local/lib/python3.8/site-packages (20.3.1)
Collecting pip
  Downloading pip-20.3.3-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 771 kB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.3.1
    Uninstalling pip-20.3.1:
      Successfully uninstalled pip-20.3.1
Successfully installed pip-20.3.3
uccessfully installed pip-20.3.3

**Comment by ichibha** [comment]
タイトルと内容が乖離してきましたので、
こちらのスレッドは閉じます。
cif2cellに関しては別スレッドで回答します。

小節2.2に関する修正のまとめ
Windowsユーザーを対象とした以下のコマンド
-----------------------------------------
% mkdir work 
および
% ln -s /work /mnt/c/Users/maezono/work
-----------------------------------------
は誤りである。ただしくは
-----------------------------------------
% mkdir /mnt/c/Users/maezono/work
および
% ln -s /mnt/c/Users/maezono/work
-----------------------------------------

既に、本著のコマンドを実行してしまっている場合には
-----------------------------------------
% cd
% rm -rf work 
% rm -rf /mnt/c/Users/maezono/work
-----------------------------------------
を実行し、2.2からやり直す。
