### ISSUE TITLE
k点パスの生成

### ISSUE THREAD

**Issue by shimizu123321** [ichibha/setupMaezono#10]
get_kpath.pyをpython3で実行できないのですが、見ていただけませんか？
　ご著書の通りにget_kpath.pyを作成したつもりですが、getとgenの使い方が間違っているかもしれません。
　何度も大変申し訳ありませんが、よろしくお願いいたします。
[get_kpath.zip](https://github.com/ichibha/setupMaezono/files/5792167/get_kpath.zip)

**Comment by ichibha** [comment]
こちらは動きますでしょうか??
インデントが分かりにくく申し訳ございません。
もし動かなければ、POSCARをください。

市場

**Comment by shimizu123321** [comment]
すみません。以下のエラーが表示され、やはり動きませんでした。

　お手数ですが、POSCARをご覧くださいますか？

maezono@DESKTOP-KV9KL02:~/work/structure$ python3 get_kpath.py
  File "get_kpath.py", line 1
    cat gen_kpath.py
        ^
SyntaxError: invalid syntax

[POSCAR.zip](https://github.com/ichibha/setupMaezono/files/5792374/POSCAR.zip)

**Comment by ichibha** [comment]
私が添付したpythonスクリプトを使いましたか??

市場

**Comment by shimizu123321** [comment]
私の見落としでしたら大変申し訳ありませんが、市場様のご返信にpythonスクリプトは添付されていましたか？

**Comment by ichibha** [comment]
メール添付ではダメなのですね。失礼しました。
下記のリンクからダウンロードできるものをお試しください。

https://www.dropbox.com/s/pcinsryktao006m/get_kpath.py?dl=0

**Comment by shimizu123321** [comment]
ありがとうございました。無事に完了しました。
