### ISSUE TITLE
擬ポテンシャルのコピー(p.89)

### ISSUE THREAD

**Issue by shimizu123321** [ichibha/setupMaezono#11]
いつもお世話になっております。
　初歩的な質問ですみませんが、ご著書通りにコマンドを入力したのですが、以下のエラーが出ました。/前後にスペースを入れるべきか省くべきかの問題かと思いますが、ご教授いただけますか？

maezono@DESKTOP-KV9KL02:~$ cp ~/ work / 01 tryout /*. UPF ~/ work /02 calibCond /.
cp: -r not specified; omitting directory '/home/maezono/'
cp: -r not specified; omitting directory 'work'
cp: -r not specified; omitting directory '/'
cp: cannot stat '01': No such file or directory
cp: cannot stat 'tryout': No such file or directory
cp: cannot stat '/*.': No such file or directory
cp: cannot stat 'UPF': No such file or directory
cp: -r not specified; omitting directory '/home/maezono/'
cp: -r not specified; omitting directory 'work'
cp: cannot stat '/02': No such file or directory
cp: cannot stat 'calibCond': No such file or directory

**Comment by ichibha** [comment]
スペースの位置が分かりづらく申し訳ございません。
.UPFで終わるファイルを全てコピーしたいということでしょうか??
下記のようにします。
#スペースは1つで良いですが分かりやすさのために4スペースにしてます。

cp    ~/work/01tryout/*.UPF    ~/work/02calibCond/.

**Comment by shimizu123321** [comment]
ありがとうございました。無事コピーできました。
