### ISSUE TITLE
結晶構造ファイルの書式変換（テキスト3.2節）に関するError

### ISSUE THREAD

**Issue by KatsuhiroArimoto** [ichibha/setupMaezono#2]
市場様

初めまして．現在，「動かして理解する第一原理電子計算状態」を読み進めており，その中で表題の操作に関してWarningとErrorが出たため，解決法をお教え願いたいと思い，連絡致しました．

AMCSDから入手・保管した4種の結晶構造ファイル：

1. alpha-クオーツ/0015462
2. beta-クオーツ/0018071
3. alpha-クリストバライト/0001629
4. beta-クリストバライト/0017665

をVESTAおよびcif2cellでQuantumEspressoの入力に与える形式に変換するという流れですが，VESTAで変換した後のファイルから，
% cif2cell -p pwscf --pwscf-cartesian-latticevectors quartz_alpha.cif
などの実行により.inファイルを作ろうとするとWarningとErrorが出てしまいます．

まず上記の4種の結晶構造ファイルのうち，1. から3. に対しては，
***Warning: Space group operation check failed for Hall symbol Unknown (H-M symbol Unknown).
というWarningがTerminalに出ます．このときにはquartz_alpha.inがテキスト通りに出力されています．一方で4. に対しては，
***Error: cell setup: Found neither Hall nor H-M symbol and space group 227 does not have a unique setting.
というErrorがTerminalに出ます．そしてこのときにはcristo_beta.inファイルが出力されません．

以上のような状態の場合に，

1. 最初の3つの場合に出るWarningは無視して良いのか？
2. 最後の場合のErrorをどのように解決できるか？

をお教え願いたいと思います．

参考までに，私の実行環境を以下に記載致します．

- PC：Mac機
- VESTA：version 3.5.5
- cif2cell：version 1.2.10

お忙しい中と存じますが，御回答よろしくお願い申し上げます．

**Comment by ichibha** [comment]
結晶構造ファイルを添付いただけますでしょうか??

市場

**Comment by KatsuhiroArimoto** [comment]
御対応くださりありがとうございます．
結晶構造ファイルは以下の通りです．
DcifFilesの中身がVESTAに入力するもの，CifFilesの中身がcif2cellに入力するものです．
[CifFiles.zip](https://github.com/ichibha/setupMaezono/files/5716712/CifFiles.zip)
[DcifFiles.zip](https://github.com/ichibha/setupMaezono/files/5716713/DcifFiles.zip)

**Comment by ichibha** [comment]
CIF2CELLのバージョンが古いことが原因かと思われます。
バージョン2.0.0を以下の手順でインストールし、リトライいただけますでしょうか??

brew install python@3.8 
python3.8 -m pip install cif2cell
# バージョン指定しないと3.9が入るが、3.9ではCIF2CELlをインストールできなかった。

ただし、cif2cellコマンドを実行するまえに、CIFファイルを編集し下記のように一行加える必要があります。
こちらは出版後のCIF2CELLの仕様変更によるものです。

-----------------------------------------
_chemical_name_common                  'Si O2'
_database_code None                                             <-- 加える
_cell_length_a                         5.013000
_cell_length_b                         5.013000
-----------------------------------------

市場

**Comment by ichibha** [comment]
下記はcatalinaではうまくいったのですが、
big surではpython3.9でも3.8でもインストールできませんでした。
こちらの方でもうすこし調べてみます。

市場

**Comment by ichibha** [comment]
beta-クリストバライト/0017665は無くても進行上問題ありませんので、
さしあたり、他のものの計算を進めていただければと思います。
warningがでたことに関し、.inを送付いただけば中身を確認します。

市場

**Comment by KatsuhiroArimoto** [comment]
市場様

遅くなりましたが、Warningに関する.inファイルを送付致しますので、御確認いただければ幸いです。よろしくお願い申し上げます。
[InFiles.zip](https://github.com/ichibha/setupMaezono/files/5740083/InFiles.zip)

**Comment by ichibha** [comment]
遅ればせながら確認させていただきました。
cif2cell ver2.0.0を使用し、当方で変換したものと相違ありませんでしたので、
こちらをお使いいただければと思います。

**Comment by ichibha** [comment]
cif2cell ver.2.0.0がMac OS Big Sur上ではインストールできない

**Comment by KatsuhiroArimoto** [comment]
市場様

御多用の中，御確認くださりありがとうございました．

ところで，以前のコメントの中にありました「macOS Catalina/Big Surにおいてcif2cell 2.0.0a2を上手くインストールできない」という問題ですが，個人的に調べた結果，下記のような方法でcif2cell 2.0.0a2およびpymatgen 2020.12.18をmacOS Big Sur 11.1上でインストールでき，cifファイルからcellファイルへの変換を含めてテキストの第3章の計算を一通り実行することができましたため，僭越ながら御報告致します．

方針としては，まずPyenvでHomebrewのPythonとは独立にPython 3.8環境を準備し，次にPoetry（Pythonのパッケージ依存管理マネージャー）でcif2cellとpymatgenを含むPythonの仮想環境を構築するという流れを取りました．Poetryでインストールする部分は，pipを利用しても問題ないと考えられます．

1. PyenvのインストールおよびPython 3.8環境の準備

まず，Pyenv本体と，Pyenvに付属してインストールが推奨されているものをHomebrewでインストールしました．

```bash
% brew install bzip2 openssl readline sqlite xz zlib pyenv
% echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.zshrc
% source ~/.zshrc
```

次に，PyenvによるPythonのインストールを，以下の"PyenvInstall.sh"というシェルスクリプトを実行して行いました．

```bash
#### ~/PyenvInstall.sh #####

#!/bin/sh

### Python version ###
VERSION="3.8.6"

### openssl, readline, sqlite, zlib ###
BREW_PACKAGES=(openssl readline sqlite zlib)
SYSROOT=$(xcrun --sdk macosx --show-sdk-path)

INCLUDES=""
LIBRARIES=""
PKGCONFIG=""
for INDEX in ${!BREW_PACKAGES[@]}; do
    BREW_PACKAGE=${BREW_PACKAGES[${INDEX}]}
    PATH_PREFIX=$(brew --prefix ${BREW_PACKAGE})
    INCLUDES="-I${PATH_PREFIX}/include ${INCLUDES}"
    LIBRARIES="-L${PATH_PREFIX}/lib ${LIBRARIES}"
    PKGCONFIG="${PATH_PREFIX}/lib/pkgconfig:${PKGCONFIG}"
done

### bzip2 ###
INCLUDES="-I$(brew --prefix bzip2)/include ${INCLUDES}"
LIBRARIES="-L$(brew --prefix bzip2)/lib ${LIBRARIES}"

### System Driver Kernel ###
INCLUDES="-I${SYSROOT}/usr/include ${INCLUDES}"
LIBRARIES="-L${SYSROOT}/usr/lib ${LIBRARIES}"

### pyenv install ###
CFLAGS="-isysroot ${SYSROOT} ${INCLUDES}"
CPPFLAGS="-isysroot ${SYSROOT} ${INCLUDES}"
LDFLAGS="${LIBRARIES}"
PCO="$PYTHON_CONFIGURE_OPTS --enable-framework --with-openssl=$(brew --prefix openssl)"

### echo "CFLAGS=${CFLAGS} CPPFLAGS=${CPPFLAGS} LDFLAGS=${LDFLAGS} PYTHON_CONFIGURE_OPTS=${PCO} pyenv install ${VERSION}"
CFLAGS=${CFLAGS} CPPFLAGS=${CPPFLAGS} LDFLAGS=${LDFLAGS} PYTHON_CONFIGURE_OPTS=${PCO} pyenv install ${VERSION}
```

シェルスクリプトの実行：

```bash
% chmod u+x ~/PyenvInstall.sh
% ~/PyenvInstall.sh
```

2. Poetryのインストールおよび仮想環境の構築

PoetryのインストールおよびPoetryによる仮想環境の構築は，基本的には[Poetryのホームページ](https://python-poetry.org)の手順に従いました．
Poetryをホームページ通りにインストールした後，上記のホームページの手順に従って，

```bash
% poetry init
```

を実行して，対話形式で後述のような"pyproject.toml"ファイルをホームディレクトリに作り，Pyenvの場合とは別のシェルスクリプト"PoetryInstall.sh"（後述）を準備してそれを，

```bash
% chmod u+x ~/PoetryInstall.sh
% ~/PoetryInstall.sh
```

と実行し，cif2cellとpymatgenを含むPythonの仮想環境の構築に成功しました．この仮想環境の有効化・無効化は，ホームディレクトリをカレントディレクトリにした上で，

```bash
% poetry shell #有効化
% exit #無効化
```
で行えます．有効化した状態で~/workディレクトリに移動し，cif2cellコマンドを実行することで，4種類のcifファイルを全てcellファイルに問題なく変換できました．

```bash
##### ~/pyproject.toml #####

[tool.poetry]
name = "QuantumEspresso"
version = "0.1.0"
description = "Python packages for QuantumEspresso."
authors = []

[tool.poetry.dependencies]
python = "^3.8"
cif2cell = "^2.0.0-alpha.2"
pymatgen = "^2020.12.18"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

```bash
##### ~/PoetryInstall.sh #####

#!/bin/sh

INCLUDES=""
LIBRARIES=""

BREW_PACKAGE="openblas"

PATH_PREFIX="$(brew --prefix ${BREW_PACKAGE})"
INCLUDES="-I${PATH_PREFIX}/include ${INCLUDES}"
LIBRARIES="-L${PATH_PREFIX}/lib ${LIBRARIES}"
PKGCONFIG="${PATH_PREFIX}/lib/pkgconfig"
OPENBLAS="${PATH_PREFIX}"

SYSROOT="$(xcrun --sdk macosx --show-sdk-path)"

INCLUDES="-I${SYSROOT}/usr/include ${INCLUDES}"
LIBRARIES="-L${SYSROOT}/usr/lib ${LIBRARIES}"
LIB_PATH="${SYSROOT}/usr/lib"

COPTION="-Wno-implicit-function-declaration"

CFLAGS="-isysroot ${SYSROOT} ${INCLUDES} ${COPTION}"
CPPFLAGS="-isysroot ${SYSROOT} ${INCLUDES} ${COPTION}"
LDFLAGS="${LIBRARIES}"

LIBRARY_PATH="${LIB_PATH}:$LIBRARY_PATH" OPENBLAS="${OPENBLAS}" CFLAGS="${CFLAGS}" CPPFLAGS="${CPPFLAGS}" LDFLAGS="${LIBRARIES}" PKG_CONFIG_PATH="${PKGCONFIG}:$PKG_CONFIG_PATH" SYSTEM_VERSION_COMPAT=1 poetry install
```
