### ISSUE TITLE
CIF2CELLのインストールに失敗した (Ubuntuエミュレータ on Windows)

### ISSUE THREAD

**Issue by ichibha** [ichibha/setupMaezono#3]
ありがとうございました。構造データを移し、VESTAで変換するところまで進めました。

　続いてなのですが、cif2cellがインストールできていなかったようで、cif2cellを実行できませんでした。2.4.1に書いてあるように、

cd
sudo pip3 install cif2cell

と入力してパスワードを入力したところ、以下の表示が出てきました。

Collecting cif2cell
  Using cached cif2cell-2.0.0a2-py2.py3-none-any.whl (2.1 MB)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from cif2cell) (1.14.0)
Collecting PyCifRW==4.4; python_version >= "3"
  Using cached PyCifRW-4.4.tar.gz (1.1 MB)
Building wheels for collected packages: PyCifRW
  Building wheel for PyCifRW (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9onaa7ot/pycifrw/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9onaa7ot/pycifrw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yj4c44pz
       cwd: /tmp/pip-install-9onaa7ot/pycifrw/
  Complete output (31 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/CifFile
  copying src/__init__.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/CifFile_module.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/yapps3_compiled_rt.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/YappsStarParser_1_1.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/YappsStarParser_1_0.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/YappsStarParser_STAR2.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/YappsStarParser_2_0.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/StarFile.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/TypeContentsParser.py -> build/lib.linux-x86_64-3.8/CifFile
  copying src/parsetab.py -> build/lib.linux-x86_64-3.8/CifFile
  creating build/lib.linux-x86_64-3.8/CifFile/drel
  copying src/drel/drel_ast_yacc.py -> build/lib.linux-x86_64-3.8/CifFile/drel
  copying src/drel/drel_lex.py -> build/lib.linux-x86_64-3.8/CifFile/drel
  copying src/drel/drel_runtime.py -> build/lib.linux-x86_64-3.8/CifFile/drel
  copying src/drel/parsetab.py -> build/lib.linux-x86_64-3.8/CifFile/drel
  copying src/drel/py_from_ast.py -> build/lib.linux-x86_64-3.8/CifFile/drel
  copying src/drel/__init__.py -> build/lib.linux-x86_64-3.8/CifFile/drel
  running build_ext
  building 'CifFile.StarScan' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/src
  creating build/temp.linux-x86_64-3.8/src/lib
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c src/lib/lex.yy.c -o build/temp.linux-x86_64-3.8/src/lib/lex.yy.o
  unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for PyCifRW
  Running setup.py clean for PyCifRW
Failed to build PyCifRW
Installing collected packages: PyCifRW, cif2cell
    Running setup.py install for PyCifRW ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9onaa7ot/pycifrw/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9onaa7ot/pycifrw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-__a4srbq/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/PyCifRW
         cwd: /tmp/pip-install-9onaa7ot/pycifrw/
    Complete output (31 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.8
    creating build/lib.linux-x86_64-3.8/CifFile
    copying src/__init__.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/CifFile_module.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/yapps3_compiled_rt.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/YappsStarParser_1_1.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/YappsStarParser_1_0.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/YappsStarParser_STAR2.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/YappsStarParser_2_0.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/StarFile.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/TypeContentsParser.py -> build/lib.linux-x86_64-3.8/CifFile
    copying src/parsetab.py -> build/lib.linux-x86_64-3.8/CifFile
    creating build/lib.linux-x86_64-3.8/CifFile/drel
    copying src/drel/drel_ast_yacc.py -> build/lib.linux-x86_64-3.8/CifFile/drel
    copying src/drel/drel_lex.py -> build/lib.linux-x86_64-3.8/CifFile/drel
    copying src/drel/drel_runtime.py -> build/lib.linux-x86_64-3.8/CifFile/drel
    copying src/drel/parsetab.py -> build/lib.linux-x86_64-3.8/CifFile/drel
    copying src/drel/py_from_ast.py -> build/lib.linux-x86_64-3.8/CifFile/drel
    copying src/drel/__init__.py -> build/lib.linux-x86_64-3.8/CifFile/drel
    running build_ext
    building 'CifFile.StarScan' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/src
    creating build/temp.linux-x86_64-3.8/src/lib
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.8 -c src/lib/lex.yy.c -o build/temp.linux-x86_64-3.8/src/lib/lex.yy.o
    unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9onaa7ot/pycifrw/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9onaa7ot/pycifrw/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-__a4srbq/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/PyCifRW Check the logs for full command output.
WARNING: You are using pip version 20.2.4; however, version 20.3.3 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.

　これはどうすれば解決できるでしょうか？すみませんが、よろしくお願いいたします。

_Originally posted by @shimizu123321 in https://github.com/ichibha/setupMaezono/issues/1#issuecomment-749548897_

**Comment by ichibha** [comment]
私の環境ではcif2cellは正常にインストールされます。python3/pip3のバージョンが古いのかもしれません。下記を実行後、もう一度cif2cellをインストールできるか確かめていただけますでしょうか??
sudo apt update
sudo apt upgrade

**Comment by ichibha** [comment]
上述のコマンド後でも、同様のエラーでcif2cellのインストールに失敗するとのこと、了解しました。

私の方でUbuntuを再度インストールし、p189の内容に従いpython3環境を再度構築し、cif2cellのインストールを行なったところ、正常にインストールされました。

私の方では問題を再現できませんので、Ubuntuのインストールからやり直されるのがもっとも確実かと思います。

**Comment by shimizu123321** [comment]
Ubuntuのアンインストールから始めました。

　Ubuntuをもう一度インストールした後、setupMaezonoをダウンロードしようとしたのですが、以下の表示が現れました。

maezono@DESKTOP-KV9KL02:~/work$ git clone https://github.com/ichibha/setupMaezono.git
Cloning into 'setupMaezono'...
error: chmod on /mnt/c/Users/ganzg/work/setupMaezono/.git/config.lock failed: Operation not permitted
fatal: could not set 'core.filemode' to 'false'

　またタイトルからずれてしまいすみませんが、これはどのように対処すればよいでしょうか？

**Comment by ichibha** [comment]
既にsetupMaezonoがあるためです。なぜならば、workはwindowsの領域にあるのでUbuntuを消しても消されません。
したがって、setupMaezonoの準備とstructureの準備は不要になります。shimizuさんの方で何が不要かの切り分けが難しければ、
workディレクトリを消してやり直すというのも一つの手となります。


市場

**Comment by shimizu123321** [comment]
無事cif2cellをダウンロードできました。ありがとうございました。
　また、pymatgenのインストールでお聞きしたいことがあります。
　引き続き、別スレッドでよろしくお願いいたします。

**Comment by ichibha** [comment]
まとめ
ubuntu@windows環境でcif2cellのインストールを試みたが、それに失敗した。
原因が不明だったため、ubuntuエミュレーターを再インストールし、一からインストールし直したところ、今度はインストールに成功した。

Ubuntuを消しても、/Users/ユーザー名/work以下のファイルは全て残るので、setupMaezonoやstructureを再び用意する必要はない。どの作業が不要かの切り分けが難しければ、workも消して全て初めからやり直す。
