### ISSUE TITLE
pymatgenのインストール

### ISSUE THREAD

**Issue by shimizu123321** [ichibha/setupMaezono#4]
いつもお世話になっております。
　ただの確認になってしまうかもしれませんが、pymatgenのインストールを行ったところ、以下のようにWARNINGが表示されました。
　最終的にはSuccessfllyが表示されたのでよいと思っておりますが、大丈夫でしょうか？

maezono@DESKTOP-KV9KL02:~$ pip3 install pymatgen
Collecting pymatgen
  Downloading pymatgen-2020.12.18.tar.gz (2.8 MB)
     |████████████████████████████████| 2.8 MB 1.3 MB/s
Collecting matplotlib>=1.5
  Downloading matplotlib-3.3.3-cp38-cp38-manylinux1_x86_64.whl (11.6 MB)
     |████████████████████████████████| 11.6 MB 1.1 MB/s
Collecting monty>=3.0.2
  Downloading monty-4.0.2-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 1.0 MB/s
Collecting networkx>=2.2
  Downloading networkx-2.5-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 2.6 MB/s
Collecting numpy>=1.14.3
  Using cached numpy-1.19.4-cp38-cp38-manylinux2010_x86_64.whl (14.5 MB)
Collecting palettable>=3.1.1
  Downloading palettable-3.3.0-py2.py3-none-any.whl (111 kB)
     |████████████████████████████████| 111 kB 4.1 MB/s
Collecting pandas
  Downloading pandas-1.2.0-cp38-cp38-manylinux1_x86_64.whl (9.7 MB)
     |████████████████████████████████| 9.7 MB 3.7 MB/s
Collecting plotly>=4.5.0
  Downloading plotly-4.14.1-py2.py3-none-any.whl (13.2 MB)
     |████████████████████████████████| 13.2 MB 4.0 MB/s
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from pymatgen) (2.22.0)
Collecting ruamel.yaml>=0.15.6
  Downloading ruamel.yaml-0.16.12-py2.py3-none-any.whl (111 kB)
     |████████████████████████████████| 111 kB 492 kB/s
Collecting scipy>=1.5.0
  Downloading scipy-1.5.4-cp38-cp38-manylinux1_x86_64.whl (25.8 MB)
     |████████████████████████████████| 25.8 MB 5.1 MB/s
Collecting spglib>=1.9.9.44
  Downloading spglib-1.16.0-cp38-cp38-manylinux2010_x86_64.whl (295 kB)
     |████████████████████████████████| 295 kB 2.8 MB/s
Collecting sympy
  Downloading sympy-1.7.1-py3-none-any.whl (5.9 MB)
     |████████████████████████████████| 5.9 MB 1.1 MB/s
Collecting tabulate
  Downloading tabulate-0.8.7-py3-none-any.whl (24 kB)
Collecting uncertainties>=3.1.4
  Downloading uncertainties-3.1.5-py2.py3-none-any.whl (246 kB)
     |████████████████████████████████| 246 kB 6.1 MB/s
Collecting cycler>=0.10
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting pillow>=6.2.0
  Downloading Pillow-8.0.1-cp38-cp38-manylinux1_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 4.8 MB/s
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.1-cp38-cp38-manylinux1_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 4.3 MB/s
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 2.3 MB/s
Collecting python-dateutil>=2.1
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 2.3 MB/s
Collecting decorator>=4.3.0
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Requirement already satisfied: pytz>=2017.3 in /usr/lib/python3/dist-packages (from pandas->pymatgen) (2019.3)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from plotly>=4.5.0->pymatgen) (1.14.0)
Collecting retrying>=1.3.3
  Downloading retrying-1.3.3.tar.gz (10 kB)
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9"
  Downloading ruamel.yaml.clib-0.2.2-cp38-cp38-manylinux1_x86_64.whl (578 kB)
     |████████████████████████████████| 578 kB 1.8 MB/s
Collecting mpmath>=0.19
  Downloading mpmath-1.1.0.tar.gz (512 kB)
     |████████████████████████████████| 512 kB 1.7 MB/s
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 5.5 MB/s
Building wheels for collected packages: pymatgen, retrying, mpmath, future
  Building wheel for pymatgen (setup.py) ... done
  Created wheel for pymatgen: filename=pymatgen-2020.12.18-cp38-cp38-linux_x86_64.whl size=4092670 sha256=2c4bd5ccfe14add5b599c654e0bcdaf01d271197dab974f25b69a96429224c2c
  Stored in directory: /home/maezono/.cache/pip/wheels/ac/1c/ad/b275333059db8216e3c15e61e9ca9317acef8d256ee4d87a37
  Building wheel for retrying (setup.py) ... done
  Created wheel for retrying: filename=retrying-1.3.3-py3-none-any.whl size=11430 sha256=2fc4e68f656c21e5cf35c72e211d251d2b9341fdc8458213a448d8c2be38c9b7
  Stored in directory: /home/maezono/.cache/pip/wheels/c4/a7/48/0a434133f6d56e878ca511c0e6c38326907c0792f67b476e56
  Building wheel for mpmath (setup.py) ... done
  Created wheel for mpmath: filename=mpmath-1.1.0-py3-none-any.whl size=532239 sha256=ef00c09f80c1582a1e1580ebbb9b2fc8304739f55a488235666388e30a133e8d
  Stored in directory: /home/maezono/.cache/pip/wheels/29/2c/1c/d2e4580cde2743b0aef389e936ac21a2db92921ddbca53faa1
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=2cf5e91ee06418210d4b2498026833ed67b41ab78bd319c86ef7c831530bb43e
  Stored in directory: /home/maezono/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
Successfully built pymatgen retrying mpmath future
Installing collected packages: cycler, pillow, kiwisolver, pyparsing, numpy, python-dateutil, matplotlib, monty, decorator, networkx, palettable, pandas, retrying, plotly, ruamel.yaml.clib, ruamel.yaml, scipy, spglib, mpmath, sympy, tabulate, future, uncertainties, pymatgen
  WARNING: The scripts f2py, f2py3 and f2py3.8 are installed in '/home/maezono/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed future-0.18.2 mpmath-1.1.0 plotly-4.14.1 pymatgen-2020.12.18 ruamel.yaml-0.16.12 ruamel.yaml.clib-0.2.2 scipy-1.5.4 spglib-1.16.0 sympy-1.7.1 tabulate-0.8.7 uncertainties-3.1.5

**Comment by ichibha** [comment]
結論から申し上げますと、こちらのwarningは問題ありません。

WARNING: The scripts f2py, f2py3 and f2py3.8 are installed in '/home/maezono/.local/bin' which is not on PATH.
こちらは、ざっといって「f2py、f2py3、f2py3.8といったスクリプトが使えない」ということを意味していますが、これらは使いませんので。
