### ISSUE TITLE
cif2cellを使ったQuantumEspressoの入力書式への変換

### ISSUE THREAD

**Issue by shimizu123321** [ichibha/setupMaezono#5]
いつもお世話になっております。cif2cellを使ったQuantumEspressoの入力書式への変換について行き詰まったため、こちらもご教授いただきたく連絡を差し上げました。

　おかげさまで、p.49まではご著書通りに進めることができました。続いて、以下のコマンドを実行したところ、エラーが出てしまいました。

maezono@DESKTOP-KV9KL02:~/work/structure$ cif2cell -p pwscf --pwscf-cartesian-latticevectors quartz_alpha.cif
***Error: cell setup: Unable to read crystallographic parameters

　これは何が問題だったのでしょうか？よろしくお願いいたします。

**Comment by ichibha** [comment]
quartz_alpha.cifを頂けますでしょうか??

**Comment by shimizu123321** [comment]
承知しました。よろしくお願いいたします。

[quartz_alpha.zip](https://github.com/ichibha/setupMaezono/files/5749665/quartz_alpha.zip)

**Comment by ichibha** [comment]
cif2cellのインストールについては別のスレに回し、こちらのスレは閉じます。

**Comment by ichibha** [comment]
私の方でもエラーを再現できました。
vestaによる変換に問題があるのかと思います。
変換前のcifを送付いただけますでしょうか??

市場

**Comment by shimizu123321** [comment]
新年早々ありがとうございます。
変換前のcifをお送りします。
引き続きよろしくお願いいたします。

[quartz_alpha (3).zip](https://github.com/ichibha/setupMaezono/files/5761293/quartz_alpha.3.zip)

**Comment by ichibha** [comment]
私の方でvestaでcifを出力しなおし、cif2cellを実行したところ、正常に変換されました。
変換したファイルを、変換後に開いたりはしていないでしょうか??
そうであれば、再度vestaから試してみてください。
または、vestaのバージョンが古いということは?



市場

**Comment by shimizu123321** [comment]
ＶＥＳＴＡをバージョンアップし、先に進むことができました。
　ありがとうございました。
