### ISSUE TITLE
gnuplotの使い方 (p.64)

### ISSUE THREAD

**Issue by shimizu123321** [ichibha/setupMaezono#8]
いつもお世話になっております。現在、3.4.3 プロッタの利用を実践しております。
　ご著書のようにscript03を作製・実行した後、gnuplotでtempに対して実行しましたが、以下のようにエラーが表示されました。これはscript03またはtempのどこかに問題があったということでしょうか？
　添付は私が作成したscript03とtempです。申し訳ありませんが、ご教授よろしくお願いいたします。
[script03.zip](https://github.com/ichibha/setupMaezono/files/5763679/script03.zip)

maezono@DESKTOP-KV9KL02:~/work/01tryout$ gnuplot

        G N U P L O T
        Version 5.2 patchlevel 8    last modified 2019-12-01

        Copyright (C) 1986-1993, 1998, 2004, 2007-2019
        Thomas Williams, Colin Kelley and many others

        gnuplot home:     http://www.gnuplot.info
        faq, bugs, etc:   type "help FAQ"
        immediate help:   type "help"  (plot window: hit 'h')

Terminal type is now 'wxt'
gnuplot> plot 'temp'
Unable to init server: Could not connect: Connection refused
17:17:48: Error: Unable to initialize GTK+, is DISPLAY set properly?
Failed to initialize wxWidgets.

Terminal type is now 'unknown'
         wxt init failure

**Comment by ichibha** [comment]
「B.3.2 Xserverのセットアップ」は行いましたでしょうか？

市場

**Comment by shimizu123321** [comment]
はい。最新のバージョンにもしたのですが、同じ結果になってしまいました。

**Comment by ichibha** [comment]
下記の2つはubuntuを立ち上げるたびにに必要になりますが、こちらはどうでしょうか??

1. Ubuntuの エミュレータを立ち上げる前にこれをダブルクリックし, Xserverを立ち上げてお くことでUbuntu上で図や画像を表示することができるようになります.
2. export DISPLAY=:0.0

gnuplotを開く直前に
echo $DISPLAY
を実行し、出力を見せていただけますでしょうか?

市場

**Comment by shimizu123321** [comment]
export DISPLAYは実行しておりませんでした。
　gnuplotを開く直前にecho $DISPLAYを実行したところ、

　1. export DISPLAY=:0.0入力前⇒何も表示されず
　2. export DISPLAY=:0.0入力後⇒:0.0と表示されました。

これは何を意味してるのでしょうか？

　また、上記2つ実行した後でgnuplotを実行したところ、以下の表示とp.59のグラフ(挿入図なし)が現れました。問題ないでしょうか？

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast

(gnuplot:75): Gtk-WARNING **: 12:29:19.610: Error loading theme icon 'edit-paste' for stock: Icon 'edit-paste' not present in theme Yaru

(gnuplot:75): Gtk-WARNING **: 12:29:19.637: Error loading theme icon 'document-save-as' for stock: Icon 'document-save-as' not present in theme Yaru

**Comment by ichibha** [comment]
たしか、export DISPLAY=:0.0は、出力先にメインのディスプレイを指定するとかだったと思います。図がみられればWarningがでても問題ないです。
