### ISSUE TITLE
作成される分散図 (p.78)

### ISSUE THREAD

**Issue by shimizu123321** [ichibha/setupMaezono#9]
いつもお世話になっております。
　p.79の分散図の表示のさせ方について質問があります。

　setupMaezonoに入っていたplotband.inをもとにqa.band.psを作成し、分散図を表示させようとしたのですが、以下のようなエラーが現れ、分散図の表示に失敗しました。
　また、setupMaezonoに入っていたqa.bandの容量は250 KB, 自分のqa.bandは10 KBでした。このように違いが出てしまった原因はどこにあるでしょうか？

　たびたびすみませんが、よろしくお願いいたします。

maezono@DESKTOP-KV9KL02:~/work/01tryout$ evince qa.band.ps
Unable to init server: Could not connect: Connection refused
Cannot parse arguments: Cannot open display:

**Comment by shimizu123321** [comment]
追記です。qa.band.xmgr.は19個まで作成されました。

**Comment by ichibha** [comment]
qa.bandの容量についてはともかく、
とりあえず、描画できないのはxserverの問題に見えます。
evinceの前にgnuplotが動くか確認してください。
> maezono@DESKTOP-KV9KL02:~/work/01tryout$ evince qa.band.ps
> Unable to init server: Could not connect: Connection refused
> Cannot parse arguments: Cannot open display:
> 
容量が少ない件についてはqeのバージョンが関係しているのかもしれません。
aptで提供されているqeのバージョンが上がったと。
バンド図の見た目が同じならば問題ないです。

市場

**Comment by shimizu123321** [comment]
export DISPLAY=:0.0を入力した後にevinceを実行したところ、グラフが表示されました。お騒がせしてすみません。

　ただ、容量が少ない件についてはいまだに解決できておりません。sudo apt ...を実行したのですが、qe, evince, gnuplotは最新でした。ほかにはどのような原因が考えられるでしょうか？

**Comment by ichibha** [comment]
得られた分散図は見た目上に違いはありますか?? 参照のものと。

**Comment by shimizu123321** [comment]
はい。縦軸に沿って、-6.0 ~ -4.0, 3.0 ~ 6.0にかけて点が集中した分散図が得られました。添付が私の得た分散図です。
[qa.band - コピー.pdf](https://github.com/ichibha/setupMaezono/files/5788903/qa.band.-.pdf)

**Comment by ichibha** [comment]
計算ファイル一式を送っていただけますでしょうか??

市場

**Comment by shimizu123321** [comment]
承知いたしました。よろしくお願いいたします。

[qa.band.xmgr.zip](https://github.com/ichibha/setupMaezono/files/5789600/qa.band.xmgr.zip)

**Comment by ichibha** [comment]
SCFから全てのファイルをいただけますでしょうか??

市場

**Comment by ichibha** [comment]
その前にp76を正しく行っているか確認してください。
市場

**Comment by shimizu123321** [comment]
すみません。p.76でミスがありました。
　無事に図3.9を再現できました。
　ありがとうございました。
